# Generated by CMake 2.8.10.2

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target opencv_core
ADD_LIBRARY(opencv_core SHARED IMPORTED)

# Create imported target opencv_flann
ADD_LIBRARY(opencv_flann SHARED IMPORTED)

# Create imported target opencv_imgproc
ADD_LIBRARY(opencv_imgproc SHARED IMPORTED)

# Create imported target opencv_highgui
ADD_LIBRARY(opencv_highgui SHARED IMPORTED)

# Create imported target opencv_features2d
ADD_LIBRARY(opencv_features2d SHARED IMPORTED)

# Create imported target opencv_calib3d
ADD_LIBRARY(opencv_calib3d SHARED IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/OpenCVModules-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
