#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     light,               sensorLightActive)
#pragma config(Sensor, S3,     compass,             sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     sonar,               sensorSONAR)
#pragma config(Motor,  motorA,          motorA,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorB,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorC,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    ,                     tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //FTC include file to "handle" the Bluetooth messages.

#include "RobotMoves.c"  //Brandeis functions for basic robot motions

//#include "HTcommon.h"  //HiTechnic infrared sensor drivers
//#include "HTIRS-driver.h"  //HiTechnic infrared sensor functions

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  initializeDriveMotors();
  return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{

  initializeRobot();

 /* TURN THIS OFF ONLY DURING DEVELOPMENT
  waitForStart();   // wait for start of tele-op phase
 TURN THIS BACK ON WHEN USING FIELD MANAGEMENT SYSTEM */
//CHANGE waitForStart() also in Joystick.c !!!!!


	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.

  while (true)
  {
    getJoystickSettings(joystick);  // Get the latest game controller / joystick settings that have been received from the PC.

    if(joystick.joy1_y1 < 20 && joystick.joy1_y1 > -20)
    {
      motor[motorD] = 0;
    }
    else
    {
      motor[motorD] = joystick.joy1_y1/2;
    }

    if(joystick.joy1_y2 < 20 && joystick.joy1_y2 > -20)
    {
      motor[motorE] = 0;
    }
    else
    {
      motor[motorE] = joystick.joy1_y2/2;
    }

    if (joystick.joy1_Buttons == 64) //left arm open
    {
      motor[motorB] = -100;
    }
    else
    {
      motor[motorB] = 0;
    }
    if (joystick.joy1_Buttons == 128)//right arm open
    {
      motor[motorC] = -100;
    }
    else
    {
      motor[motorC] = 0;
    }
    if (joystick.joy1_Buttons == 16) //left arm close
    {
      motor[motorB] = 50;
    }
    else
    {
      motor[motorB] = 0;
    }

    if (joystick.joy1_Buttons == 32)//right arm close
    {
      motor[motorC] = 50;
    }
    else
    {
      motor[motorC] = 0;
    }
    if(joystick.joy1_Buttons == 1)
    {
      PlaySound(soundBeepBeep);
      //driveContinuous(30);
    }
    if(joystick.joy1_Buttons == 2)
    {
      PlaySound(soundDownwardTones);
      driveStop();
    }
    if(joystick.joy1_Buttons == 4)
    {
      PlaySound(soundLowBuzz);
      //turnLeft(20);
    }
    if(joystick.joy1_Buttons == 8)
    {
      PlaySound(soundBlip);
      //turnRight(20);
    }
    if(joystick.joy1_Buttons == 256)
    {
      PlayTone(3000, 100);
      driveDistance(40, 1000);
    }
    if(joystick.joy1_Buttons == 512)
    {
    }

 }
}
