#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     HTDIR,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,                    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,         sensorSONAR)
#pragma config(Motor,  motorA,          motorA,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorB,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorC,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

//function protoypes
void robotMove1bs();
void robotMove1as();
void initializeDriveMotors();
void bluel();
void bluer();
void redl();
void redr();
void spinner();
void backUpMove();

int LValue;
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  if (true)
  {
    motor[motorD]=40;
    motor[motorE]=40;
    bluel();
    //bluer();
    //redl();
    //redr();
  }
}
void bluel()
{
  int count=0;
  while (count<3)
  {
    if(SensorValue[lightSensor] > 50)
    {
      LValue= SensorValue[lightSensor];
      wait10Msec(35);
      count++;

    }
  }
  initializeDriveMotors()
    while(nMotorEncoder[motorD] <1500)
  {
   motor[motorD]=50;
   motor[motorE]=-50;
  }


   motor[motorD]=-50;
   motor[motorE]=-50;
   wait10Msec(100);
}
void bluer()
{
  initializeDriveMotors();
  while(nMotorEncoder[motorD] <1200)
  {
    motor[motorD]=40;
    motor[motorE]=40;
  }
  initializeDriveMotors()
  while(nMotorEncoder[motorE] <1600)
  {
    motor[motorD]=-40;
    motor[motorE]=40;
  }
    motor[motorD]=0;
    motor[motorE]=0;
    wait10Msec(10);
    motor[motorD]=-50;
    motor[motorE]=-50;
    wait10Msec(100);
}
void redl()
{
  initializeDriveMotors();
  while(nMotorEncoder[motorD] <950)
  {
    motor[motorD]=40;
    motor[motorE]=40;
  }
  initializeDriveMotors()
  while(nMotorEncoder[motorD] <1500)
  {
    motor[motorD]=40;
    motor[motorE]=-40;
  }
    motor[motorD]=0;
    motor[motorE]=0;
    wait10Msec(10);
    motor[motorD]=-50;
    motor[motorE]=-50;
    wait10Msec(100);
}
void redr()
{
  int count=0;
  while (count<3)
  {
    if(SensorValue[lightSensor] > 50)
    {
      LValue= SensorValue[lightSensor];
      wait10Msec(35);
      count++;

    }
  }
   motor[motorD]=-50;
   motor[motorE]=50;
   wait10Msec(100);
   motor[motorD]=-50;
   motor[motorE]=-50;
   wait10Msec(100);
}
void spinner()
{
  motor[motorB]=100;
  motor[motorC]=100;
}

void initializeDriveMotors()
{
  nMotorEncoder[motorD] = 0;
  nMotorEncoder[motorE] = 0;
}
