#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    ,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    ,                     tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    ,                     tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{


waitForStart();
  while (true)
  {

    getJoystickSettings(joystick);
    if(joystick.joy1_y1 < 30 && joystick.joy1_y1 > -30)
    {
      motor[motorD] = 0;
    }
    else
    {
      motor[motorD] = joystick.joy1_y1/2;
    }

    if(joystick.joy1_y2 < 30 && joystick.joy1_y2 > -30)
    {
      motor[motorE] = 0;
    }
    else
    {
      motor[motorE] = -joystick.joy1_y2/2;
    }



    if(joystick.joy1_Buttons == 1);
    {
      servo[servo1] = 150;
    }
    else
   // if (joystick.joy1_Buttons == 2);
    {
      servo[servo1] = 40;
    }

  }
}
