#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Motor,  motorA,          motorA,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorB,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorC,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
//waitForStart();


  while (true)
  {

    getJoystickSettings(joystick);  // Get the latest game controller / joystick settings that have been received from the PC.

    if(joystick.joy1_y1 < 20 && joystick.joy1_y1 > -20)
    {
      motor[motorD] = 0;
     // motor[motorE] = 0;
     // motor[motorF] = 0;
      //motor[motorF] = 0;
      //motor[motorG] = 0;

    }
    else
    {

      motor[motorD] = -joystick.joy1_y1;
    //  motor[motorE] = joystick.joy1_y1/2;
      //motor[motorF] = joystick.joy1_y1/2;
      //motor[motorF] = -joystick.joy1_y1/2;
      //motor[motorG] = joystick.joy1_y1/2;// F not working
    }

    if(joystick.joy1_y2 < 20 && joystick.joy1_y2 > - 20)
    {
      motor[motorE] = 0;
    }

    else
    {
      motor[motorE] = joystick.joy1_y2;
    }

    /*else if (joystick.joy1_y1 < -30)
    {

     //if not working

    }
*/
/*
   if(joystick.joy1_y2 < 30 && joystick.joy1_y2 > -30)
    {
      motor[motorF] = 0;
      motor[motorE] = 0;
    }
    else if (joystick.joy1_y2 > 30)
    {
      motor[motorF] = joystick.joy1_y2/2;
      motor[motorE] = joystick.joy1_y2/2;

    }
    else if (joystick.joy1_y2 > -30) // 1B7
    {
      motor[motorF] = -joystick.joy1_y2/2;
      motor[motorE] = -joystick.joy1_y2/2;
    }*/

 }
}
